version: "3.3"
services:
  application:
    build: .
    container_name: html-parser
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    container_name: html_postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
